# Numpy

In [21]:
import numpy as np

In [74]:
data = [[32,23],
        [5,2],
        [49,23]]

In [75]:
twoDarray = np.array(data, dtype=np.float64)

In [76]:
print(twoDarray)

[[32. 23.]
 [ 5.  2.]
 [49. 23.]]


In [77]:
updatedArray = twoDarray + 3.2

In [78]:
print(updatedArray)

[[35.2 26.2]
 [ 8.2  5.2]
 [52.2 26.2]]


In [79]:
twoDarray2 = np.array ([np.ones(2), np.ones(2), np.ones(2)], dtype=np.float64 )

In [80]:
print(twoDarray2)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [81]:
print(np.ndim(twoDarray2))

2


In [82]:
print(np.ndim(updatedArray))

2


In [87]:
print(np.dot([twoDarray2], updatedArray))

ValueError: shapes (1,3,2) and (3,2) not aligned: 2 (dim 2) != 3 (dim 0)

#### the above produces error because the number of columns of one doesnt match the number of rows of the other

In [89]:
#the dot product works because the number of rows and columns are the same
dot =np.dot([[1,2],[4,2]], [[3,2],[5,3]])
print(dot)

[[13  8]
 [22 14]]


In [132]:
dot[1]

array([22, 14])

In [96]:
np.sum(dot[0])

21