# Numpy

In [21]:
import numpy as np

In [22]:
data = [[32,23],
        [5,2],
        [49,23]]

In [23]:
twoDarray = np.array(data)

In [24]:
print(twoDarray)

[[32 23]
 [ 5  2]
 [49 23]]


In [25]:
updatedArray = twoDarray + 3.2

In [26]:
print(updatedArray)

[[35.2 26.2]
 [ 8.2  5.2]
 [52.2 26.2]]


In [52]:
twoDarray2 = np.array (
             [np.ones(2), np.ones(2), np.ones(2)] )

In [53]:
print(twoDarray2)

[[1. 1.]
 [1. 1.]
 [1. 1.]]
